### ISSUE TITLE
View Advert Details and Tracking Data

### ISSUE THREAD

**Issue by Samyoul** [arfaoui47/ad_tracker#11]
![home](https://cloud.githubusercontent.com/assets/5702426/21640267/9974afd4-d26c-11e6-969e-07ab72c94835.png)

Currently there is no link on tracked advert list items to view the tracked advert's details or tracking data.

**Comment by Samyoul** [comment]
![home](https://cloud.githubusercontent.com/assets/5702426/21686705/3844ae1a-d35e-11e6-98d1-d4b8233fb7d7.png)

The current implementation doesn't show any useful information. Please refer to these requirements:

**Displaying Tracking Information:**

>Please remember as per the specifications that the adverts not only need to be found, they need to be authorised by a system user and then **after authorisation the advert needs to be tracked, logging the time and location the advert appears.** I notice the the repository does not have a database model for logging this information, I would suggest you add this to the code.

Does the current implementation record **each** time a tracked advert is found by the application?

If so, only show summary information on the advert view page. Summary information is defined as total number of times the advert has been found on a total number of websites.

Give the user a link to click in order to view the tracking data list.

**Displaying Advert Details**

In the advert model https://github.com/arfaoui47/ad_tracker/blob/master/dashboard/models.py#L30 you have a lot of information that is not being displayed. Further there is no frontend functionality to edit the data.

```
class Advert(db.Model):
    __tablename__ = 'images'
    __searchable__ = ['description']
    
    id = db.Column(db.Integer, primary_key=True)
    checksum = db.Column(db.String(256))
    date_creation = db.Column(db.DateTime(100))
    year = db.Column(db.Integer)
    month = db.Column(db.String)
    date = db.Column(db.String)
    url = db.Column(db.String(250))
    website = db.Column(db.String(100))
    file_type = db.Column(db.String(50))
    original_url = db.Column(db.String(500))
    authorized = db.Column(db.String(50))
    description = db.Column(db.String(500))
    rate = db.Column(db.Integer)
    value = db.Column(db.Float, onupdate=rate/30)
    banner_size = db.Column(db.String(50))
    product = db.Column(db.String(100))
    class_customer = db.Column(db.String(100))
    category = db.Column(db.String(100))
    sector = db.Column(db.String(100))
    image_id = db.Column(db.String(100))
```

**Comment by arfaoui47** [comment]
Yes, the current implementation does record logging when we find an advert with authorized value equals to True. So I'll  move displaying the tracking data from the separate page to advert view page and display only how much advert is found in every website.

**Comment by Samyoul** [comment]
Do you have an estimated datetime of completion for this issue? Thanks
